services:
  - type: cron
    name: run-airdrop-script
    env: node
    numInstances: 1
    schedule: "*/3 * * * *"
    startCommand: "wget https://github.com/holaplex/hub-starter-subscription-airdrops/releases/download/1.0/airdrop-linux-amd64 -O airdrop && chmod +x ./airdrop && RUST_LOG=debug ./airdrop"
    envVars:
      - fromGroup: airdrop-env
      - key: DATABASE_URL
        fromDatabase:
          name: hub-starter-template
          property: connectionString
  - type: web
    name: hub-starter-template
    env: node
    numInstances: 1
    buildCommand: npm install; npm run build
    startCommand: npm run start
    envVars:
      - fromGroup: airdrop-env
      - key: DATABASE_URL
        fromDatabase:
          name: hub-starter-template
          property: connectionString
    autoDeploy: true

databases:
  - name: hub-starter-template
    ipAllowList: []

envVarGroups:
  - name: airdrop-env
    envVars:
    - key: GOOGLE_CLIENT_ID
      sync: false
    - key: GOOGLE_CLIENT_SECRET
      sync: false
    - key: HOLAPLEX_AUTH_TOKEN
      sync: false
    - key: HOLAPLEX_PROJECT_ID
      sync: false
    - key: HOLAPLEX_DROP_ID
      sync: false
    - key: NEXTAUTH_URL
      sync: false
    - key: NEXTAUTH_SECRET
      generateValue: true
    - key: HOLAPLEX_WALLET_ASSET_TYPE
      value: SOL
    - key: HOLAPLEX_API_ENDPOINT
      value: https://api.holaplex.com/graphql
