services:
  - type: worker
    name: run-airdrop-script
    env: node
    numInstances: 1
    #schedule: "*/4 * * * *"
    #startCommand: npm install; npx prisma generate; npm run airdrop
    buildCommand: npm install; npx prisma generate
    startCommand: "bash -c 'while true;do npm run airdrop; sleep 120;done'"
    envVars:
    - key: HOLAPLEX_PROJECT_ID
      sync: false
    - key: HOLAPLEX_AUTH_TOKEN
      sync: false
    - key: HOLAPLEX_API_ENDPOINT
      value: https://api.holaplex.com/graphql
    - key: DATABASE_URL
      fromDatabase:
        name: hub-starter-template
        property: connectionString
  - type: web
    name: hub-starter-template
    env: node
    numInstances: 1
    buildCommand: npm install; npm run build
    startCommand: npm run start
    envVars:
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: HOLAPLEX_AUTH_TOKEN
        sync: false
      - key: HOLAPLEX_PROJECT_ID
        sync: false
      - key: HOLAPLEX_DROP_ID
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: HOLAPLEX_WALLET_ASSET_TYPE
        value: SOL
      - key: HOLAPLEX_API_ENDPOINT
        value: https://api.holaplex.com/graphql
      - key: DATABASE_URL
        fromDatabase:
          name: hub-starter-template
          property: connectionString

    autoDeploy: true

databases:
  - name: hub-starter-template
    ipAllowList: []
