name: Release

on:
  push:
    branches:
      - main
      - release
      - mpw/ci_setup

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
        - x86_64-unknown-linux-musl
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Prepare env
        run: |
          cat << EOF > .env
          DATABASE_URL=postgres://postgres:holaplex@localhost:5432/hub-starter
          POSTGRES_DB=hub-starter
          POSTGRES_USER=postgres
          POSTGRES_PASSWORD=holaplex
          EOF

      - uses: isbang/compose-action@v1.4.1
        name: Start Postgres with docker-compose
        with:
          compose-file: ./docker-compose.yaml

      - name: Install packages and run migrations
        run: |
          npm install
          npm run migrate

      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          export $(xargs < .env)
          cp holaplex.graphql ./scripts/airdrop && cd scripts/airdrop
          docker run --network host --rm -t \
            -e DATABASE_URL=$DATABASE_URL \
            -v $HOME/.cargo/registry/:/root/.cargo/registry \
            -v "$(pwd)":/volume \
            clux/muslrust:stable \
            cargo build --release --target ${{ matrix.target }}

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: airdrop-${{ matrix.os }}-amd64
          path: target/${{ matrix.target }}/release/airdrop
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download
        uses: actions/download-artifact@v2
      - name: Layout
        run: |
          mv airdrop-ubuntu-latest-amd64/airdrop ./airdrop-linux-amd64
          rm -rf airdrop-ubuntu-latest-amd64

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          generate_release_notes: true
          draft: true
          fail_on_unmatched_files: true
          files: |
            airdrop-linux-amd64
